### ISSUE TITLE
debug print has been uploaded to pypi

### ISSUE THREAD

**Issue by EvanTheB** [MisanthropicBit/colorise#2]
https://github.com/MisanthropicBit/colorise/blob/e630df74b8b27680a43c370ddbe98766be50158c/colorise/nix/ColorManager.py#L65

**Comment by MisanthropicBit** [comment]
Thanks! Good catch.

If you interesting in the project. It is currently being revived from its pretty dead state on [`rgb_256_exts` branch](https://github.com/MisanthropicBit/colorise/tree/rgb_256_exts). I will fix the PyPi issue over the weekend.

**Comment by MisanthropicBit** [comment]
Version 0.1.4 has been marked as a [pre-release](https://github.com/MisanthropicBit/colorise/releases/tag/v0.1.4) and a new version 1.0.0 is now the official first release of `colorise`.
